name: Apply PGO

on:
  workflow_dispatch:

jobs:
  apply-pgo:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - run: |
          sudo apt-get update
          sudo apt-get install -y cmake libtinfo5

      - uses: KyleMayes/install-llvm-action@v2
        with:
          version: "18.1.8"
          cached: false

      - run: |
          OPT_LEVEL="3"
          SIZE_LEVEL="1"

          chmod +x ./wamrc

          ./wamrc --target=x86_64 \
                  --opt-level=${OPT_LEVEL} \
                  --size-level=${SIZE_LEVEL} \
                  --enable-simd \
                  --cpu=x86-64-v3 \
                  --enable-llvm-pgo \
                  --format=aot \
                  -o src/Physics/binary/x86_64/HavokPhysics.aot \
                  src/Physics/binary/HavokPhysics.wasm

          zig build
          ./zig-out/bin/havok

          ${{ env.LLVM_PATH }}/bin/llvm-profdata merge -output=HavokPhysics.profdata HavokPhysics.profraw

          ./wamrc --target=x86_64 \
                  --opt-level=${OPT_LEVEL} \
                  --size-level=${SIZE_LEVEL} \
                  --enable-simd \
                  --cpu=x86-64-v3 \
                  --use-prof-file=HavokPhysics.profdata \
                  --format=aot \
                  -o src/Physics/binary/x86_64/HavokPhysicsPGO.aot \
                  src/Physics/binary/HavokPhysics.wasm

          chmod +x ./iwasm
          ./iwasm src/Physics/binary/x86_64/HavokPhysicsPGO.aot

      - uses: actions/upload-artifact@v6
        with:
          name: apply-pgo-result
          path: src/Physics/binary/x86_64/HavokPhysicsPGO.aot
