name: Build Wamrc

on:
  workflow_dispatch:

jobs:
  build-wamrc:
    runs-on: windows-latest

    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14.3' 

      - run: |
          git clone https://github.com/bytecodealliance/wasm-micro-runtime.git
          cd wasm-micro-runtime

          cd wamr-compiler
          python -m pip install requests
          python build_llvm.py
          mkdir build && cd build
          cmake ..
          cmake --build . --config Release

      - uses: actions/upload-artifact@v6
        with:
          name: wamrc
          path: wasm-micro-runtime/wamr-compiler/build/Release/wamrc.exe
