name: Build Wamrc

on:
  workflow_dispatch:

jobs:
  build-wamrc:
    runs-on: ubuntu-22.04

    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install git build-essential cmake g++-multilib libgcc-9-dev lib32gcc-9-dev ccache

      - run: |
          git clone https://github.com/bytecodealliance/wasm-micro-runtime.git
          cd wasm-micro-runtime

          cd wamr-compiler
          ./build_llvm.sh
          mkdir build && cd build
          cmake ..
          make

      - uses: actions/upload-artifact@v6
        with:
          name: wamrc
          path: wasm-micro-runtime/wamr-compiler/build/wamrc
