on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  pages: write
  contents: read
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - run: zig build-lib src/Physics/HavokPhysics.zig -femit-docs
        continue-on-error: true

      - uses: actions/upload-pages-artifact@v2
        with:
          path: ./docs/

  deploy:
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
