name: WAMR PGO Linux test

on:
  workflow_dispatch:

jobs:
  verify-pgo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - run: |
          WAMR_VERSION="2.4.4"

          wget https://github.com/bytecodealliance/wasm-micro-runtime/releases/download/WAMR-${WAMR_VERSION}/wamrc-${WAMR_VERSION}-x86_64-ubuntu-22.04.tar.gz

          tar -xvf wamrc-${WAMR_VERSION}-x86_64-ubuntu-22.04.tar.gz

          sudo mv wamrc /usr/local/bin/

      - run: |
          chmod +x ./iwasm

          wamrc --enable-llvm-pgo --format=aot -o add_one_plus_one.aot add_one_plus_one.wasm

          ./iwasm --gen-prof-file=add_one_plus_one.profraw -f add_one_plus_one add_one_plus_one.aot

      - uses: actions/upload-artifact@v6
        with:
          name: wamr-pgo-results
          path: |
            add_one_plus_one.profraw
