name: WAMR PGO Linux test

on:
  workflow_dispatch:

jobs:
  verify-pgo:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - run: |
          sudo apt-get update
          sudo apt-get install -y cmake libtinfo5

      - uses: KyleMayes/install-llvm-action@v2
        with:
          version: "18.1.8"
          cached: true

      - run: |
          WAMR_VERSION="2.4.4"

          wget https://github.com/bytecodealliance/wasm-micro-runtime/releases/download/WAMR-${WAMR_VERSION}/wamrc-${WAMR_VERSION}-x86_64-ubuntu-22.04.tar.gz

          tar -xvf wamrc-${WAMR_VERSION}-x86_64-ubuntu-22.04.tar.gz

          sudo mv wamrc /usr/local/bin/

      - run: |
          chmod +x ./iwasm

          wamrc --target=x86_64 \
                --cpu=x86-64-v3 \
                --opt-level=3 \
                --size-level=1 \
                --enable-simd \
                --enable-llvm-pgo \
                --format=aot \
                -o src/Physics/binary/x86_64/HavokPhysics.aot \
                src/Physics/binary/HavokPhysics.wasm

          zig build
          ./zig-out/bin/havok

          ${{ env.LLVM_PATH }}/bin/llvm-profdata merge -output=HavokPhysics.profdata HavokPhysics.profraw

          wamrc --target=x86_64 \
                --cpu=x86-64-v3 \
                --opt-level=3 \
                --size-level=1 \
                --enable-simd \
                --use-prof-file=HavokPhysics.profdata \
                --format=aot \
                -o src/Physics/binary/x86_64/HavokPhysics.aot
                src/Physics/binary/HavokPhysics.wasm

      - uses: actions/upload-artifact@v6
        with:
          name: wamr-pgo-results
          path: src/Physics/binary/x86_64/HavokPhysics.aot
